baseURL = 'https://firebleu.website/'
languageCode = 'en-us'
title = 'Firebleu Website'
theme = 'hyde'

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Accueil"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "script"
    name = "Mon script"
    url = "/script/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "Qui suis-je"
    url = "/about/"
    weight = 4
